### ISSUE TITLE
"Socket accept failed" after upgrading gPRC Spring version to 3.1.0.RELEASE

### ISSUE THREAD

**Issue by billwenboli** [grpc-ecosystem/grpc-spring#1131]
**The context**

gRPC Spring Version Upgrade Issue

**The question**

I have encountered startup issue after upgrading gRPC Spring version to 3.1.0.RELEASE from 2.15.0.RELEASE. The error is shown below. Has anyone encountered this before and what is the solution to fix this? Thanks.

**Stacktraces and logs**

11:47:02.044 [http-nio-8080-Acceptor] ERROR org.apache.tomcat.util.net.Acceptor - Socket accept failed
java.nio.channels.AsynchronousCloseException: null
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.end(ServerSocketChannelImpl.java:376)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:399)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:521)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:79)
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:128)
	at java.base/java.lang.Thread.run(Thread.java:840)
11:47:02.123 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - 

**The application's environment**

Which versions do you use?
* Spring (boot): 3.1.8
* grpc-java: 1.63.0
* grpc-spring-boot-starter: 3.1.0.RELEASE
* java: 17 + ARM-64
* Other relevant libraries...

**Comment by billwenboli** [comment]
Does anyone have an answer to this? Thanks.
